# Generated by Django 4.2.4 on 2023-08-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('userName', models.CharField(blank=True, max_length=255, null=True)),
                ('orderComment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
