# Generated by Django 4.2.4 on 2023-08-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_producttype_options_product_shortdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isPromotionActive',
            field=models.BooleanField(default=False, verbose_name='Отображать акционный блок?'),
        ),
    ]
