# Generated by Django 4.2.4 on 2023-08-13 17:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_ispromotionactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgalleryimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[420, 420], upload_to='product/gallery'),
        ),
    ]
