# Generated by Django 4.2.4 on 2023-08-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_totalprice_alter_cartitem_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
