# Generated by Django 4.2.4 on 2023-08-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='cart',
            new_name='order',
        ),
    ]
